### ISSUE TITLE
use server with http api calls 

### ISSUE THREAD

**Issue by sirifarif** [laurensw75/docker-Kaldi-NL#4]
Is there any way, we can modify the scripts to prepare the server for HTTP API call. So that it can be used with GET and POST methods.
thanks

**Comment by laurensw75** [comment]
You can do ASR on files if you use `curl -T myfile.wav "http://localhost:8888/client/dynamic/recognize"`, not sure if a more complicated REST API would add much in the context of what this docker is supposed to do.

**Comment by sirifarif** [comment]
@laurensw75 thanks, figured it out.
